"""Memory provenance + trust schema (Sprint 2).

Every memory entry should know:
  - where it came from           (source_type, source_id)
  - who generated it             (generated_by, generation_lineage)
  - confidence at creation       (creation_confidence)
  - usefulness over time         (usefulness_score, usefulness_samples)
  - failure history              (failure_count, last_failure_ts)
  - trust score                  (computed from above)

This module defines the CANONICAL field set. All ingest paths funnel through
`build_provenance()` so the metadata shape is uniform.

Backward-compatible: every field has a sane default; existing memories without
these fields are treated as `source_type="legacy"`, `trust_score=0.5`.
"""
from __future__ import annotations

import time
from dataclasses import dataclass, field, asdict
from typing import Any, Dict, List, Optional


# ── Source types ───────────────────────────────────────────────────────── #

SOURCE_USER         = "user"          # user-provided content (highest trust)
SOURCE_TOOL         = "tool"          # deterministic tool output
SOURCE_FILE         = "file"          # ingested from disk
SOURCE_AGENT        = "agent"         # generated by an internal agent
SOURCE_GLOBAL       = "global"        # retrieved from SuperMemory
SOURCE_CAPTURE      = "capture"       # passive screen/AX capture
SOURCE_LEGACY       = "legacy"        # pre-Sprint 2; treated as middle-trust


# Default trust by source. Tunable per deployment.
_DEFAULT_TRUST: Dict[str, float] = {
    SOURCE_USER:    0.95,
    SOURCE_TOOL:    0.80,
    SOURCE_FILE:    0.70,
    SOURCE_AGENT:   0.55,    # generated outputs — lower until validated
    SOURCE_GLOBAL:  0.65,    # SuperMemory has its own ranking, still external
    SOURCE_CAPTURE: 0.50,
    SOURCE_LEGACY:  0.50,
}


# ── Provenance dataclass ───────────────────────────────────────────────── #

@dataclass
class Provenance:
    """Canonical provenance payload merged into memory metadata.

    Stored INSIDE the existing `metadata` dict under key `provenance`,
    so vector-store schemas stay unchanged.
    """
    source_type: str = SOURCE_LEGACY
    source_id:   Optional[str] = None    # tool_name, file_path, agent name, etc.
    generated_by: Optional[str] = None   # specific agent/user identifier
    generation_lineage: List[str] = field(default_factory=list)  # chain of agents
    creation_confidence: float = 0.5     # 0..1 — caller's estimate at creation
    creation_ts: float = field(default_factory=time.time)
    task_id: Optional[str] = None        # task that produced this memory

    # Usefulness — accumulated over retrieval feedback
    usefulness_score: float = 0.5        # running mean in [0, 1]
    usefulness_samples: int = 0          # how many feedback events
    last_used_ts: Optional[float] = None
    failure_count: int = 0
    last_failure_ts: Optional[float] = None

    def trust_score(self) -> float:
        """Derived trust in [0, 1]. Compositional:
            base = source-default trust
            adjusted = base * (1 - failure_penalty) + usefulness_lift

        failure_penalty grows as failure_count rises.
        usefulness_lift weights the running usefulness mean by its sample count.
        """
        base = _DEFAULT_TRUST.get(self.source_type, 0.5)
        # Failure penalty: 5% per failure, capped at 60% reduction
        penalty = min(0.6, self.failure_count * 0.05)
        # Usefulness lift: weighted by samples (more samples → more weight)
        # confidence_in_score = samples / (samples + 5)  — Bayesian smoothing
        conf = self.usefulness_samples / (self.usefulness_samples + 5)
        lift = (self.usefulness_score - 0.5) * conf * 0.4   # max ±0.2
        score = base * (1 - penalty) + lift
        return round(max(0.0, min(1.0, score)), 4)

    def as_dict(self) -> Dict[str, Any]:
        d = asdict(self)
        d["trust_score"] = self.trust_score()
        return d

    @classmethod
    def from_dict(cls, data: Optional[Dict[str, Any]]) -> "Provenance":
        if not data:
            return cls()
        # tolerate extra keys (trust_score is derived, not stored)
        known = {f.name for f in cls.__dataclass_fields__.values()}
        return cls(**{k: v for k, v in data.items() if k in known})


# ── Helpers used by ingest paths ───────────────────────────────────────── #

def build_provenance(
    *,
    source_type: str,
    source_id: Optional[str] = None,
    generated_by: Optional[str] = None,
    creation_confidence: float = 0.5,
    task_id: Optional[str] = None,
    generation_lineage: Optional[List[str]] = None,
) -> Provenance:
    """Construct a fresh Provenance with safe defaults."""
    return Provenance(
        source_type=source_type,
        source_id=source_id,
        generated_by=generated_by,
        creation_confidence=max(0.0, min(1.0, creation_confidence)),
        task_id=task_id,
        generation_lineage=list(generation_lineage or []),
    )


def attach_provenance(metadata: Optional[Dict[str, Any]], prov: Provenance) -> Dict[str, Any]:
    """Return a new metadata dict with provenance merged in. Idempotent.

    Stores under `metadata["provenance"]` (a nested dict) plus a top-level
    `trust_score` mirror for cheap querying.
    """
    out = dict(metadata or {})
    out["provenance"] = prov.as_dict()
    out["trust_score"] = prov.trust_score()
    out.setdefault("source_type", prov.source_type)
    if prov.generated_by:
        out.setdefault("generated_by", prov.generated_by)
    if prov.task_id:
        out.setdefault("origin_task_id", prov.task_id)
    return out


def extract_provenance(metadata: Optional[Dict[str, Any]]) -> Provenance:
    """Read provenance from metadata, falling back to legacy default."""
    if not metadata:
        return Provenance()
    raw = metadata.get("provenance")
    if isinstance(raw, dict):
        return Provenance.from_dict(raw)
    # Legacy memory — synthesize from top-level hints
    return Provenance(
        source_type=str(metadata.get("source_type", SOURCE_LEGACY)),
        source_id=metadata.get("source") or metadata.get("source_id"),
        generated_by=metadata.get("generated_by"),
        task_id=metadata.get("task_id") or metadata.get("origin_task_id"),
    )


def merge_feedback(prov: Provenance, *, usefulness_delta: float,
                   failure: bool = False) -> Provenance:
    """Return new Provenance with feedback merged (running-mean update)."""
    new_samples = prov.usefulness_samples + 1
    # Incremental mean: μ_n = μ_{n-1} + (x_n - μ_{n-1}) / n
    new_mean = prov.usefulness_score + (usefulness_delta - prov.usefulness_score) / new_samples
    return Provenance(
        source_type=prov.source_type,
        source_id=prov.source_id,
        generated_by=prov.generated_by,
        generation_lineage=list(prov.generation_lineage),
        creation_confidence=prov.creation_confidence,
        creation_ts=prov.creation_ts,
        task_id=prov.task_id,
        usefulness_score=round(max(0.0, min(1.0, new_mean)), 4),
        usefulness_samples=new_samples,
        last_used_ts=time.time(),
        failure_count=prov.failure_count + (1 if failure else 0),
        last_failure_ts=time.time() if failure else prov.last_failure_ts,
    )
